services:
  - type: web
    name: budget-app-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: budget-app-db
          property: connectionString
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@yourdomain.com
      - key: FRONTEND_URL
        value: https://budget-app-adbaf.web.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://budget-app-adbaf.web.app,http://localhost:3000
        #sync: false
      - key: ALLOWED_HOSTS
        value: budget-app-5xsv.onrender.com
      - key: GOOGLE_OAUTH2_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        sync: false

  - type: cron
    name: budget-alerts-cron
    env: python
    schedule: "*/30 * * * *"  
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py run_alerts --type=all
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-app-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: budget-app-db
    plan: free
